spring.application.name=game-expert
spring.datasource.url=jdbc:mysql://localhost:13306/game
spring.datasource.username=root
spring.datasource.password=1234

server.port=8000

spring.jpa.hibernate.ddl-auto=update

spring.data.redis.host=localhost
spring.data.redis.port=6379
